const npcAlmanach = {
    "lordwhite": {
        "name": "Derral Sitsk",
        "role": "Lord White of Brightend",
        "quote": "Order and prosperity",
        "image": "./images/lord_white.png",
        "homePinTitle": "Alabaster Palace",
        "settlement": "Cloud District",
        "species": "Human",
        "age": "54",
        "gender": "Male",
        "affiliation": "The Crown",
        "relationToParty": "Neutral",
        "biography": "Derral Sitsk was the youngest Lord White of Brightend. He distinguished himself at 29 while succesfully protecting the city of Marshes with his troops. His military accomplishments pushed him into politics. <br> Alec Teal's father, Fearn, promoted Sitsk to Lord Commander. A successful campaign to free The city-state Lemerolai got him the title of Lord White after the death of the previous holder.",
        "secrets": "fdhbizueghb Hzo lmjPIF Hndz njz!rem"
    },
    "hammer_nim": {
        "name": "Hammer",
        "role": "Candy maker",
        "quote": "Nothing beats a candy! Except a knife",
        "image": "images/hammer.jpg",
        "homePinTitle": "Hammer's Candy",
        "settlement": "Cloud District",
        "species": "Dwarf",
        "age": "36",
        "gender": "Female",
        "affiliation": "Independent",
        "relationToParty": "Ally",
        "biography": "Once a renowned drug dealer/adventurer, she dated Nimo. Now she changed her life and dropped her bad habits... both of them.",
        "secrets": ""
    },
    "wardenfoll": {
        "name": "Ledon Foll",
        "role": "Militia Captain",
        "quote": "Brightend is its people",
        "image": "images/ledon_foll.png",
        "homePinTitle": "Warden Fort",
        "settlement": "Cloud District",
        "species": "Earth Genasi",
        "age": "49",
        "gender": "Male",
        "affiliation": "Alabaster Wardens",
        "relationToParty": "Ally",
        "biography": "Grand Warden Foll is well respect amongst his peers, but also revered by most citizens who recognize his dedication to the city. The towering Earth Genasi with granite-grey skin has spent his life in service of Brightend.",
        "secrets": ""
    },
    "maeravoss": {
        "name": "Maera Voss",
        "role": "Scholar",
        "quote": "Knowledge, always",
        "image": "images/maera_voss.png",
        "homePinTitle": "Hammer's Candy",
        "settlement": "Cloud District",
        "species": "Madaru",
        "age": "52",
        "gender": "Female",
        "affiliation": "Independent",
        "relationToParty": "Ally",
        "biography": "An independant scholar, specialized in paleolinguistics and antique history of the Boundless Vale. She was recently asked by Runebridge to translate a magically encrypted tome recovered in a dig site",
        "secrets": ""
    },
    "mertonlensher": {
        "name": "Merton Lensher",
        "role": "Innkeeper",
        "quote": "Drinking when we are not thirsty, eating when not hungry and fucking all year round is what differentiates us from common beasts",
        "image": "images/mertonlensher.png",
        "homePinTitle": "Gilded Goldfinch",
        "settlement": "Cloud District",
        "species": "Human",
        "age": "41",
        "gender": "Male",
        "affiliation": "Independent",
        "relationToParty": "Neutral",
        "biography": "With a broad, inviting smile and striking, heterochromatic eyes�, one clear blue and one green, he commands the polished bar of his prestigious inn. A prosperous figure with a thick mane of greying brown hair and a matching full beard, Merton is dressed in a rugged yet finely detailed leather apron over a rich, gold-embroidered green tunic. His hands rest casually on the dark counter, a symbol of sturdy, welcoming hospitality in his grand, candlelit establishment.",
        "secrets": ""
    },
    "erikthayne": {
        "name": "Erik Thayne",
        "role": "Retired",
        "quote": "\"One day at a time\"",
        "image": "images/erikthayne.png",
        "homePinTitle": "Thayne Household ",
        "settlement": "Cloud District",
        "species": "Human",
        "age": "63",
        "gender": "Male",
        "affiliation": "Independent",
        "relationToParty": "Displeased",
        "biography": "This former carpenter was married to Elira Thayne, who died in her home in mysterious circumstances. He is left heartbroken. ",
        "secrets": ""
    },
    "talonoperative": {
        "name": "Mystery man",
        "role": "??",
        "quote": "??",
        "image": "images/mysteryman.png",
        "homePinTitle": "??",
        "settlement": "Cloud District",
        "species": "Half-elf",
        "age": "??",
        "gender": "Male",
        "affiliation": "??",
        "relationToParty": "Killed",
        "biography": "A strange man tailing and taking notes of the party's whereabouts. Killed when trying to escape. ",
        "secrets": ""
    }
};
